import React from 'react'
import { motion } from 'framer-motion'
import { Shield,  } from 'lucide-react'

export const TermsPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-craft-50 via-background to-craft-100 py-20">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute inset-0" style={{
            backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23D2691E' fill-opacity='0.4'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
          }} />
        </div>
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative">
          <motion.h1
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl sm:text-6xl font-display font-bold text-gray-900 mb-6"
          >
            Terms and <span className="text-primary-600">Conditions</span>
          </motion.h1>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-xl text-gray-600 mb-8"
          >
            Please read these terms and conditions carefully before using our service.
          </motion.p>
          
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="text-sm text-gray-500"
          >
            Last updated: August 15, 2025
          </motion.div>
        </div>
      </section>

      {/* Privacy Content */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Overview */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="mb-12"
          >
            <div className="bg-primary-50 p-2 rounded-lg mb-8">
              <div className="flex items-center mb-4">
                <Shield className="text-primary-600 mr-4" size={24} />
                <h2 className="text-xl font-semibold text-gray-900">Shipping Policy</h2>
              </div>
                   <p className="text-gray-700 leading-relaxed">Our products will be delivered with in 5 -7 working days.</p><br/>
              <div className="flex items-center mb-4">
                <Shield className="text-primary-600 mr-4" size={24} />
                <h2 className="text-xl font-semibold text-gray-900">Our Commitment</h2>
              </div>
              <p className="text-gray-700 leading-relaxed">
               


This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://craftitems.netlify.app/ ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').

The Platform is owned by CHENNU JAYA SRI, a company incorporated under the Companies Act, 1956 with its registered office at West Godavari 534202 Bhimavaram ,Bhimavaram ,India (hereinafter referred to as ?Platform Owner?, 'we', 'us', 'our')..

Your use of the Platform and services and tools are governed by the following terms and conditions (?Terms of Use?) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates..

 For the purpose of these Terms of Use, wherever the context so requires ?you?, 'your' or ?user? shall mean any natural or legal person who has agreed to become a user/buyer on the Platform..

ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING..

The use of Platform and/or availing of our Services is subject to the following Terms of Use:

To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform..

Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law..

Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements..

The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics..

You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws..

You agree to pay us the charges associated with availing the Services..

You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.

You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information..

You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services..

You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.

Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event..

These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India..

All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bhimavaram and Andhra Pradesh.

All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website




Return & Refund Policy - Products should return within 5-7 working days and once if the refund is approved by our end it will take 7-10 working days to process and credited to you original mode of payment  

              </p>
            </div>
          </motion.div>
          </div>
          </section>
    </div>
  )
}